damage_map = {
    "jalur lcd": "ganti lcd",
    "error/hank": "error / hang",
    "error/hank/restart": "error / hang",
    "tombol/error": "ganti tombol",
    "tombol": "ganti tombol",
    "gantitombol": "ganti tombol",
    "tombol luar": "ganti tombol",
    "ganti tombol luar": "ganti tombol",
    "tombol power": "ganti tombol",
    "lem lcd tombol": "ganti tombol",
    "repair tombol": "ganti tombol",
    "pasang tombol": "ganti tombol",
    "tombol volume": "ganti tombol",
    "error sim card": "error / hang",
    "papan charge": "pasang papan charge",
    "c. papan charge": "pasang papan charge",
    "repair papan charge": "ganti papan charge",
    "pasang kamera depan": "pasang kamera",
    "repair back camera": "pasang kamera",
    "repair camera": "pasang kamera",
    "camera": "pasang kamera",
    "ganti camera": "ganti kamera",
    "lem back cover": "pasang back cover",
    "back cover": "ganti back cover",
    "ganti cover": "ganti back cover",
    "connector": "ganti connector charge",
    "connector charge": "ganti connector charge",
    "conector charge": "ganti connector charge",
    "ganti flexiblle finger": "ganti flexible fingerprint",
    "flexible finger": "ganti flexible fingerprint",
    "finger": "ganti flexible fingerprint",
    "ganti finger": "ganti flexible fingerprint",
    "ganti flexible finger": "ganti flexible fingerprint",
    "jalur gambar": "ic gambar",
    "ganti baterai ori cabutan": "ganti baterai",
    "ganti casing": "ganti casing",
    "ganti casing set": "ganti casing",
    "pasang casing": "ganti casing",
    "pasang casing fullset": "ganti casing",
    "pasang casing set": "ganti casing",
    "ganti flexible on/off/volume": "flexible on/off",
    "ganti flexible board (soket)": "flexible mic / board",
    "ganti flexible": "flexible mic / board"
}