waktu_mapping = {
    "ganti lcd": "30 Menit - 1 Jam",
    "pasang lcd": "15 - 30 Menit",
    "ganti baterai": "30 Menit - 1 Jam",
    "buka pola / pin / password": "2 - 4 jam",
    "software": "1 - 2 Jam",
    "ganti tombol": "10 Menit",
    "flexible on/off": "1 - 2 Jam",
    "ganti papan charge": "30 Menit - 1 Jam",
    "mati total": "3 Jam",
    "error / hang": "3 Hari",
    "flexible mic / board": "1 - 2 Jam",
    "ganti connector charge": "30 Menit - 1 Jam",
    "ic charge": "1 - 2 Jam",
    "jalur charge": "1 - 2 Jam",
    "speaker": "1 - 2 Jam",
    "no chargeing": "1 - 2 Jam",
    "pasang papan charge": "30 Menit - 1 Jam",
    "ic gambar": "2 - 5 Hari",
    "masuk air": "1 - 2 Jam",
    "ganti back cover": "15 - 30 Menit",
    "ganti flexible fingerprint": "30 Menit - 1 Jam",
    "socket mesin": "30 menit - 1 Jam",
    "mic / audio": "1 - 2 Jam",
    "ganti casing": "30 Menit - 1 Jam",
    "soket mesin": "30 Menit - 1 Jam",
    "koslet": "2 - 5 Hari",
    "no charging": "1 - 2 Jam",
}
